from .ai_chat import ai_chat
from .information import info_provider
from .system_actions import system_actions
from .web_actions import web_actions
from .calculator import smart_calculator
from .entertainment import entertainment
from .knowledge import knowledge_base
from .news import news_fetcher
from .notes import notes_manager
from .planner import task_planner
from .reminders import reminder_manager
from .sentiment import sentiment_analyzer
from .summarizer import text_summarizer
from .translator import translator
from .security_tools import security_tools
from .file_manager import file_manager
